/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author COOLBOX_SSD5
 */
/*Función de detección numérica que lea la cadena y devuelva si es una cadena String
si es una cadena entera con su valor numérico, si es una cadena decimal con su valor numérico
indicando si el caracter de definición decimal es "." o ","*/
public class Valores extends javax.swing.JFrame {

    /**
     * Creates new form Valores
     */
    public Valores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        verificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadena a verificar:");

        resultado.setBackground(new java.awt.Color(0, 153, 153));

        verificar.setText("Verificar");
        verificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verificarMouseClicked(evt);
            }
        });
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verificar)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verificar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificarMouseClicked

   
    }//GEN-LAST:event_verificarMouseClicked

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
       String tipo_dato[]=verifica_datos(dato.getText());
       resultado.setText("Es " + tipo_dato[0] + " y su valor numérico es " + tipo_dato[1]);
    }//GEN-LAST:event_verificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Valores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Valores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Valores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Valores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Valores().setVisible(true);
            }
        });
    }
    private String[] verifica_datos(String dato){
        String matriz[]=new String[2];
        byte caracteres[]=new byte[dato.length()];
        boolean cad_seminum=true;
        /*Los caracteres con significado matemático son: 
        "+" con código ASCII 43
        "-" con código ascii 45
        "." con código ascii 46 caracter decimal matemático
        "," con código ascii 44 caracter decimal español
        "/" con código ascii 47
        0-9 con código ascii entre 48 y 57*/
        caracteres=dato.getBytes();
        for(int i=0;i<dato.length();i++){
            if(caracteres[i]<43 || caracteres[i]>57 || caracteres[i]==47){
                // No es un número y se puede romper el bucle
                matriz[0]="Cadena de texto";
                matriz[1]="0";
                cad_seminum=false;
                break;
            }
            else if((caracteres[i]==43 && i>0) || (caracteres[i]==45 && i>0)){
                matriz[0]="Cadena de texto";
                matriz[1]="0";
                cad_seminum=false;
                break;
            }
        }
        if(cad_seminum==true){
            //Hay un punto decimal y solo uno. Además no hay coma
            if((dato.indexOf(".",dato.indexOf(".")+1)==-1)&&(dato.indexOf(".")!=-1)&&(dato.indexOf(",")==-1)){
                matriz[0]="Cadena decimal matemática";
                if(dato.indexOf(".")==0){
                    matriz[1]="0"+dato;
                }
                else if((dato.indexOf("+")==0) || (dato.indexOf("-")==0)&&(dato.indexOf(".")==1)){
                    //Para que +.6 aparezca como +0.6
                    matriz[1]=dato.substring(0,1)+"0."+dato.substring(2,dato.length());
                }
                else{
                    matriz[1]=dato;
                }
            }
            //Hay una coma decimal y solo uno. Además no hay punto
            else if((dato.indexOf(",",dato.indexOf(",")+1)==-1)&&(dato.indexOf(",")!=-1)&&(dato.indexOf(".")==-1)){
                matriz[0]="Cadena decimal española";
                if(dato.indexOf(",")==0){
                    matriz[1]="0"+dato;
                }
                else if((dato.indexOf("+")==0) || (dato.indexOf("-")==0)&&(dato.indexOf(",")==1)){
                    //Para que +,6 aparezca como +0,6
                    matriz[1]=dato.substring(0,1)+"0,"+dato.substring(2,dato.length());
                }
                else{
                    matriz[1]=dato;
                }
            }
            else if((dato.indexOf(",")==-1)&&(dato.indexOf(".")==-1)){
                matriz[0]="Cadena de números enteros";
                matriz[1]=dato;
            }
            else{
                matriz[0]="Cadena de texto";
                matriz[1]="0";
            }
        }
        return matriz;    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
